apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: test-gateway-route
  namespace: default
spec:
  parentRefs:
    - name: traefik-gateway
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /foo
      filters:
        - type: ExtensionRef
          extensionRef:
            group: traefik.io
            kind: Middleware
            name: test-stripprefix
      backendRefs:
        - name: foo-service
          port: 80
          weight: 1
    - matches:
        - path:
            type: PathPrefix
            value: /bar
      filters:
        - type: ExtensionRef
          extensionRef:
            group: traefik.io
            kind: Middleware
            name: test-stripprefix
      backendRefs:
        - name: bar-service
          port: 80
          weight: 1
    - matches:
        - path:
            type: PathPrefix
            value: /foobar
      filters:
        - type: ExtensionRef
          extensionRef:
            group: traefik.io
            kind: Middleware
            name: test-stripprefix
      backendRefs:
        - name: foo-bar-service
          port: 80
          weight: 1

  
  